kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ancestor-oconda
  namespace: workspace-creator
spec:
  output:
    to:
      kind: DockerImage
      name: 'docker.io/isbur/ancestor:oconda'
    pushSecret:
      name: dockerhub.pushsecret
  resources:
    limits:
      cpu: '2'
      memory: 1Gi
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: 'docker.io/isbur/ancestor:conda_fresh'
  postCommit:
    command: ["/bin/bash", "-c", "/tmp/scripts/test/run"]
  source:
    type: Git
    git:
      uri: 'https://github.com/isbur-eclipse/ancestor.git'
      ref: oconda
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secretReference:
          name: github.webhook.secret
  runPolicy: Serial
